// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Fitness_Coaching_Platform.Models;

#nullable disable

namespace OnlineFitnessCoachingPlatform.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231129075448_mig_1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AntrenmanProgrami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EgsersizAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hedef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrograminSuresi")
                        .HasColumnType("int");

                    b.Property<int>("SetTekrarSayilari")
                        .HasColumnType("int");

                    b.Property<string>("VideoRehberleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("YapanId");

                    b.ToTable("antrenmanProgramlari");
                });

            modelBuilder.Entity("Entities.Models.Antrenor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deneyimleri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzmanlikAlanlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "Eposta");

                    b.ToTable("antrenorler");
                });

            modelBuilder.Entity("Entities.Models.BeslenmeProgrami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<string>("GunlukOgunler")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Hedef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<int>("YapanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("YapanId");

                    b.ToTable("beslenmeProgramlari");
                });

            modelBuilder.Entity("Entities.Models.Gelisme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<float>("KasKütlesi")
                        .HasColumnType("real");

                    b.Property<float>("Kilo")
                        .HasColumnType("real");

                    b.Property<float>("VucutKitleIndeksi")
                        .HasColumnType("real");

                    b.Property<float>("VucutYagOrani")
                        .HasColumnType("real");

                    b.Property<int>("YapanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YapanId");

                    b.ToTable("gelismeler");
                });

            modelBuilder.Entity("Entities.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etkinlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilFotosu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "Eposta");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("Entities.Models.KullaniciAntrenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<int>("DanisanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("kullaniciAntrenor");
                });

            modelBuilder.Entity("Entities.Models.Mesajlasma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("mesajlasmalar");
                });

            modelBuilder.Entity("Entities.Models.AntrenmanProgrami", b =>
                {
                    b.HasOne("Entities.Models.Kullanici", "AlanKullanici")
                        .WithMany("AntrenmanProgramlari")
                        .HasForeignKey("AliciId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Antrenor", "YapanAntrenor")
                        .WithMany("AntrenmanProgramlari")
                        .HasForeignKey("YapanId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlanKullanici");

                    b.Navigation("YapanAntrenor");
                });

            modelBuilder.Entity("Entities.Models.Antrenor", b =>
                {
                    b.HasOne("Entities.Models.Kullanici", "Kullanici")
                        .WithMany("Antrenorlar")
                        .HasForeignKey("Id")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Entities.Models.BeslenmeProgrami", b =>
                {
                    b.HasOne("Entities.Models.Kullanici", "AlanKullanici")
                        .WithMany("BeslenmeProgramlari")
                        .HasForeignKey("AliciId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Antrenor", "YapanAntrenor")
                        .WithMany("BeslenmeProgrami")
                        .HasForeignKey("YapanId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlanKullanici");

                    b.Navigation("YapanAntrenor");
                });

            modelBuilder.Entity("Entities.Models.Gelisme", b =>
                {
                    b.HasOne("Entities.Models.Kullanici", "Kullanici")
                        .WithMany("Gelismeler")
                        .HasForeignKey("YapanId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Entities.Models.Antrenor", b =>
                {
                    b.Navigation("AntrenmanProgramlari");

                    b.Navigation("BeslenmeProgrami");
                });

            modelBuilder.Entity("Entities.Models.Kullanici", b =>
                {
                    b.Navigation("AntrenmanProgramlari");

                    b.Navigation("Antrenorlar");

                    b.Navigation("BeslenmeProgramlari");

                    b.Navigation("Gelismeler");
                });
#pragma warning restore 612, 618
        }
    }
}
